baseURL = "https://jnerk.github.io"
languageCode = "en-us"
title = "Jnerk"
theme = "archie"
copyright = "© JE Vasshaug"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourDisqusShortname"

#paginate = 5 # articles per page

[params]
mode = "toggle"                                   # color-mode → light,dark,toggle or auto
useCDN = false                                    # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "Welcome to my corner on the internet"
mathjax = false                                   # enable MathJax support
katex = false                                     # enable KaTeX support

# Social Tags

# [[params.social]]
# name = "GitHub"
# icon = "github"
# url = "https://github.com/jnerk"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/athulcajay/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4
